name: ThirstBar
version: '${project.version}'
main: me.orineko.thirstbar.ThirstBar
api-version: 1.20.6
softdepend: [PlaceholderAPI, ProtocolLib, WorldGuard]
commands:
  ThisrtBar:
    description: This is command main.
  TB:
    description: This is command main.
  Refresh:
    description: This is command main.
  RefreshAll:
    description: This is command main.
